### ISSUE TITLE
about  Zoom in and add more details

### ISSUE THREAD

**Issue by zhanghongyong123456** [IceClear/StableSR#1]
1. Looking forward to the release of the code, 
2. may I ask whether our project can achieve enlargement and add more details,What projects can be implemented

**Comment by IceClear** [comment]
Hi, thanks for your interest of our work.
1. Our code has already been released. Feel free to have a try :)
2. I am sorry I do not quite get your meaning. May I know what details you would like to know? Currently this project is mainly for image super-resolution, i.e., generating the high quality image given its low-resolution counterpart. Zoom in means we upsample the low-resolution images using bicubic upsampling. Just for comparison.

**Comment by zhanghongyong123456** [comment]
> Hi, thanks for your interest of our work.
> 
> 1. Our code has already been released. Feel free to have a try :)
> 2. I am sorry I do not quite get your meaning. May I know what details you would like to know? Currently this project is mainly for image super-resolution, i.e., generating the high quality image given its low-resolution counterpart. Zoom in means we upsample the low-resolution images using bicubic upsampling. Just for comparison. We may enlarge our project to image restoration in the future, including image debluring, denoising, colonization, etc.

For example, zoom in 16 times. After zooming in, fill in richer details in the new image based on the adjacent information of the original image.

**Comment by IceClear** [comment]
> > Hi, thanks for your interest of our work.
> > 
> > 1. Our code has already been released. Feel free to have a try :)
> > 2. I am sorry I do not quite get your meaning. May I know what details you would like to know? Currently this project is mainly for image super-resolution, i.e., generating the high quality image given its low-resolution counterpart. Zoom in means we upsample the low-resolution images using bicubic upsampling. Just for comparison. We may enlarge our project to image restoration in the future, including image debluring, denoising, colonization, etc.
> 
> For example, zoom in 16 times. After zooming in, fill in richer details in the new image based on the adjacent information of the original image.

Hi.
I am not sure of that since our model is mainly for real-world SR and we usually directly deal with real low-resolution images rather than further add degradation, e.g., zoom in on them. 
But since our code now is fully available, feel free to play around with it and share your findings. We are happy to extend it with your help.
