### ISSUE TITLE
Socket problem

### ISSUE THREAD

**Issue by 1001kathy** [IceClear/StableSR#102]
Thanks for your awesome work! I want to know when I tend to train time-aware encoder,why after print "Encoder Restored from .../.../.../v2-1_512-ema-pruned.ckpt with 0 missing and 1242 unexpected keys",then traceback directly jump to site-package and show "socket.timeout: timed out". I'm sure that my web is good on use.Looking forward to your apply!
![2023-11-23 11-28-40屏幕截图](https://github.com/IceClear/StableSR/assets/102499055/b3d7f00a-7d87-47f0-9b66-bff7a5cd74be)

**Comment by IceClear** [comment]
It seems like a problem from huggingface. You may try multiple times.

**Comment by 1001kathy** [comment]
ok,thanks!
