### ISSUE TITLE
is "python main.py --train --base configs/stableSRNew/v2-finetune_text_T_512.yaml --gpus GPU_ID, --name NAME --scale_lr False" still runable?

### ISSUE THREAD

**Issue by Maydaybye** [IceClear/StableSR#116]
I kept meeting this problem
File "/home/sddsj/anaconda3/envs/stablesr/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1375, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
because HfFileMetadata.commit_hash = None.
how to fix this problem?
commit_hash=r.headers.get(HUGGINGFACE_HEADER_X_REPO_COMMIT)   # HUGGINGFACE_HEADER_X_REPO_COMMIT = "HUGGINGFACE_HEADER_X_LINKED_ETAG"
I wonder if this code doesn't work because things have changed in huggingface

**Comment by IceClear** [comment]
I suppose it is similar to this [issue](https://github.com/huggingface/transformers/issues/23404)?

**Comment by Maydaybye** [comment]
well it is actually quite different

r.headers is a  dic returned from https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin

`r.headers = {'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '1236', 'Connection': 'keep-alive', 'Date': 'Wed, 17 Jan 2024 14:55:16 GMT', 'X-Powered-By': 'huggingface-moon', 'X-Request-Id': 'Root=1-65a7ea54-2b7745a074ac74a71eb6244d;e04ed70c-dfba-4557-9b67-d4c76a2359a3', 'Access-Control-Allow-Origin': 'https://huggingface.co', 'Vary': 'Origin, Accept', 'Access-Control-Expose-Headers': 'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,ETag,Link,Accept-Ranges,Content-Range', 'X-Repo-Commit': 'de081ac0a0ca8dc9d1533eed1ae884bb8ae1404b', 'Accept-Ranges': 'bytes', 'X-Linked-Size': '3944692325', 'X-Linked-ETag': '"9a78ef8e8c73fd0df621682e7a8e8eb36c6916cb3c16b291a082ecd52ab79cc4"', 'Location': 'https://cdn-lfs.huggingface.co/repos/a4/00/a400d3407dcb6ba1378f2783695f545ab7ba55b1b8bbea86f0eb7ab8793c3a98/9a78ef8e8c73fd0df621682e7a8e8eb36c6916cb3c16b291a082ecd52ab79cc4?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27open_clip_pytorch_model.bin%3B+filename%3D%22open_clip_pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1705760765&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwNTc2MDc2NX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy9hNC8wMC9hNDAwZDM0MDdkY2I2YmExMzc4ZjI3ODM2OTVmNTQ1YWI3YmE1NWIxYjhiYmVhODZmMGViN2FiODc5M2MzYTk4LzlhNzhlZjhlOGM3M2ZkMGRmNjIxNjgyZTdhOGU4ZWIzNmM2OTE2Y2IzYzE2YjI5MWEwODJlY2Q1MmFiNzljYzQ%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=IKuj4PzlqQ-Pe6OKE2-RvCwts0u9c9bHU7a9uACojMJUjRyxqxISzMAAQlWJqnlnPkAJsihZVqFGfMc3MTEfa-65XzEvSzE5%7EJ1WtFFEXkyYLuTOEXm5F%7E9F5hsNNTnUMxUBhLIemWAXaHdYjZL426fpz%7EsXWY7WTxNR1qYFBJkCeBPUr4-H9ysWkcPe-G-Jv848rlZsZSEGNFPO1%7Eog19OWt3%7E6ULNd80TiZ2rZOt-xUYxy5RmzhgeO1XuIpR-Zg1RYHObwkF%7EAf7mW0P6IN5nWAdxheHZjYHVKtdMdY-TQYJuBEuKpiUHZwmHjHq%7EzgIsTZse2dTuN9bvpu0ynWg__&Key-Pair-Id=KVTP0A1DKRTAX', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 eac5ff8c8951bc7fa5bbf706c830ab88.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'SFO5-P1', 'X-Amz-Cf-Id': 'JNkIWKJN063MqfmszK2olO9AyeRy3BtNhz8yE1KtvtiBvAVfyVXpvA=='} `
and 
`commit_hash=r.headers.get(HUGGINGFACE_HEADER_X_REPO_COMMIT)
HUGGINGFACE_HEADER_X_REPO_COMMIT = "HUGGINGFACE_HEADER_X_LINKED_ETAG"`
in python3.9/site-packages/huggingface_hub/file_download.py
the point is "HUGGINGFACE_HEADER_X_LINKED_ETAG" is not exist in r.headers and it returns None to commit_hash

`            if commit_hash is None:
                raise FileMetadataError(
                    "Distant resource does not seem to be on huggingface.co. It is possible that a configuration issue"
                    " prevents you from downloading resources from https://huggingface.co. Please check your firewall"
                    " and proxy settings and make sure your SSL certificates are updated."
                )`

I would like to ask whether this problem is caused by the website, and how do you solve it when you run the code，or maybe  you've never had this problem before...?

**Comment by IceClear** [comment]
I think it is a network problem. I never met such a problem.

**Comment by Maydaybye** [comment]
Ok. Anyway, thank you for your paitient answer!

**Comment by continue1213** [comment]
> I kept meeting this problem File "/home/sddsj/anaconda3/envs/stablesr/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1375, in hf_hub_download raise LocalEntryNotFoundError( huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on. because HfFileMetadata.commit_hash = None. how to fix this problem? commit_hash=r.headers.get(HUGGINGFACE_HEADER_X_REPO_COMMIT) # HUGGINGFACE_HEADER_X_REPO_COMMIT = "HUGGINGFACE_HEADER_X_LINKED_ETAG" I wonder if this code doesn't work because things have changed in huggingface

I encountered the same issue. Have you resolved this problem? And can you share the solution with me?

**Comment by Maydaybye** [comment]
https://github.com/IceClear/StableSR/issues/11#issuecomment-1558748632
you may find soloutions here
