### ISSUE TITLE
How to prepare CFW_trainingdata?

### ISSUE THREAD

**Issue by Kravrolens** [IceClear/StableSR#12]
Thanks for your great work! I'm trying to understand your training pipeline. 

I would like to know how to prepare `CFW_trainingdata` in the second step as you mentioned in README file. The data folder contains inputs, gts, latents and samples. 

It seems the `CFW_trainingdata`  comes from the diffusion model pretrained in the first stage. But I still don't know how to generate the data.

Greatly appreciate your response.

**Comment by IceClear** [comment]
Hi.
The latents can be obtained from [here](https://github.com/IceClear/StableSR/blob/main/scripts/sr_val_ddpm_text_T_vqganfin_old.py#L315), and the samples can be obtained from [here](https://github.com/IceClear/StableSR/blob/main/scripts/sr_val_ddpm_text_T_vqganfin_old.py#L316). For the gts, they are 512x512 patches and inputs are obtained following RealESRGAN degradation pipeline.

**Comment by Kravrolens** [comment]
It seems the script of `sr_val_ddpm_text_T_vqganfin_old.py` runs with the pretrained `vq_model` and LR images. 

I don't know if my understanding is correct. The latents should obtained from the HR images while running without pretrained `vq_model (VQGAN encoder)`

Could you please provide a code to generate this data? THANKS!

**Comment by IceClear** [comment]
You just need to save the results as I showed you previously. The latent are not from HR, they are the output of the Unet.

**Comment by Kravrolens** [comment]
```
init_image = init_image_list[n]
init_latent_generator, enc_fea_lq = vq_model.encode(init_image)
init_latent = model.get_first_stage_encoding(init_latent_generator)
......
samples, _ = model.sample(cond=semantic_c, struct_cond=init_latent, batch_size=init_image.size(0),
                                          timesteps=opt.ddpm_steps, time_replace=opt.ddpm_steps, x_T=x_T,
                                          return_intermediates=True)
```

The latents (samples) comes from init_latent, init_latent comes from `vq_model`, but we don't have pretrained model of VQGAN, I don't know how to save the latents as you showed before.

The latents are not from HR, they are the outputs of the Unet. But the inputs of the Unet are HR images, is it correct?

**Comment by IceClear** [comment]
> ```
> init_image = init_image_list[n]
> init_latent_generator, enc_fea_lq = vq_model.encode(init_image)
> init_latent = model.get_first_stage_encoding(init_latent_generator)
> ......
> samples, _ = model.sample(cond=semantic_c, struct_cond=init_latent, batch_size=init_image.size(0),
>                                           timesteps=opt.ddpm_steps, time_replace=opt.ddpm_steps, x_T=x_T,
>                                           return_intermediates=True)
> ```
> 
> The latents (samples) comes from init_latent, init_latent comes from `vq_model`, but we don't have pretrained model of VQGAN, I don't know how to save the latents as you showed before.
> 
> The latents are not from HR, they are the outputs of the Unet. But the inputs of the Unet are HR images, is it correct?

StableSR needs VQGAN to convert image into latents so you have pretrained model. It is inside the StableSR pretrained model.
This is the code for inference so the inputs of Unet are not HR images.
All you need to do is to first generate synthetic data following RealESRGAN pipeline and save the data locally.
Then use the inference code do the inference and save the latents and samples.

**Comment by zhenxili96** [comment]
@IceClear  Hi, to get the latents from the unet for training CFW, how many `ddpm_steps` should we use ?

**Comment by IceClear** [comment]
> @IceClear Hi, to get the latents from the unet for training CFW, how many `ddpm_steps` should we use ?

I used 200 steps, but you may also use mixed steps for better robustness. It is easy to train and steps seem not a vital factor.

**Comment by kangxi1818** [comment]
Thank you for your interesting work, but I don't know how to use the RealESRGAN pipeline

**Comment by kangxi1818** [comment]
thank you for your interesting work, I have a question about the dataset
I now have the inputs and the gts, when I geting the latent and samples, how to set the parameters --init-img of sr_val_ddpm_text_T_vqganfin_old.py to get the latent and samples, and the shape of init_latent is[1,4,64,64]
![image](https://github.com/IceClear/StableSR/assets/117744200/5afc981b-48cf-4e68-a53a-b04ab738088c)
how to save it as .npy
![image](https://github.com/IceClear/StableSR/assets/117744200/c54bfa19-0380-49fa-8980-c33cbc2ee35c)
and how to save the samples as .png

**Comment by kangxi1818** [comment]
> know how to prepare `CFW_trainingdata` in the second ste

Hello,Have you successfully obtained the training data of CFW training, and may I ask you about the code that processes the data, thank you very much
