### ISSUE TITLE
batch size is 192 in training? CUDA OOM

### ISSUE THREAD

**Issue by zhenxili96** [IceClear/StableSR#13]
Hi, I'm trying to train stablesr by the command you provided:
`python main.py --train --base configs/stableSRNew/v2-finetune_text_T_512.yaml --gpus GPU_ID, --name NAME --scale_lr False`

As your mentioned, the training batch size is 192, so I modified line 131 to "batch size: 192" and line 137 to "queue_size: 192". But it got the error "CUDA out of memory" when running. If I just keep the config file unmodified (batch size: 6, queue_size: 180), the training process can run well.

So, is the batch size 192 as mentioned in paper? If so, how should I modify the config file? Thanks in advance.

**Comment by IceClear** [comment]
Hi.
For the batchsize, we train on 8 V100 GPUs with 6 batches on each GPU and also use the accumulated batch for 4.
You do not need to adjust any parameters in the training config.
You just need to train on 8 GPUs.

**Comment by zhenxili96** [comment]
Hi, I just noticed that, when I keep` batch_size:6`, the GPU memory usage is 54895MiB. If the batch_size is changed to `batch_size: 1`, the GPU memory usage is 35697MiB. The peak usage is even more when it starts runing.

Is it consistent with your expectation? Do you know why it takes so much memory?

**Comment by IceClear** [comment]
> Hi, I just noticed that, when I keep` batch_size:6`, the GPU memory usage is 54895MiB. If the batch_size is changed to `batch_size: 1`, the GPU memory usage is 35697MiB. The peak usage is even more when it starts runing.
> 
> Is it consistent with your expectation? Do you know why it takes so much memory?

The peak VRAM with batch 6 on a V100 GPU is around 25G. You should carefully check your env.

**Comment by zhenxili96** [comment]
Hi, I tested the training process with some "abalation tests" by removing each model in the first stage training process (eg. struct_cond model, cond model, diff-unet-model), and constructing an arbitrarily pipeline to make sure the training process could run with other models.

I found that:
1. without runing diff-unet-model in forward, it takes about 19651MB. 
2. runing diff-unet-model in forward, but don't take its output as the final output in calculating loss, it takes about 30kMB.
3. runing diff-unet-model in forward, and using its output to calculate loss (the same as original process), it takes more than 32GB, OOM happens.

Do you have any clue to solve this?

I also checked my env:
torch: 1.12.1
tochvision: 0.13.1
torchmetrics: 0.6.0
python: 3.7.10
pytorch-lightning: 1.4.2
transformers: 4.29.0
nvcc --vesion: 10.2
open-clip-torch: 2.20.0

**Comment by IceClear** [comment]
Not sure. You may use xformers and make sure the stable diffusion model is fixed with require_grad = False.
