### ISSUE TITLE
finetune

### ISSUE THREAD

**Issue by flynnamy** [IceClear/StableSR#14]
Hi,if I want to finetune on my datasets based on your model.It seems that if I set the ckpt path with stablesr_000117-001.ckpt,it would have errors of missing key.Please support finetune,thanks! @IceClear

**Comment by flynnamy** [comment]
I use the command(python main.py --train --base configs/stableSRNew/v2-finetune_text_T_512.yaml --gpus GPU_ID, --name NAME --scale_lr False) of train has same error,any suggestions? @IceClear 
Traceback (most recent call last):
  File "/home/StableSR-main/main.py", line 550, in <module>
    model = instantiate_from_config(config.model)
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 353, in __getattr__
    self._format_and_raise(
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigAttributeError: Missing key model
    full_key: model
    object_type=dict

**Comment by IceClear** [comment]
Current release support finetuning already.
It seems that it is more like a version issue.
Please try to reinstall omegaconf with a suitable version.

**Comment by flynnamy** [comment]
I install pytorch-lightning==1.4.2 and omegaconf==2.1.1.Which version should I install? @IceClear

**Comment by flynnamy** [comment]
I solved it by reinstall. How to do finetune? I replace the ckpt path(line22) with stablesr_000117-001.ckpt and the ckpt path(line55) with vqgan_cfw_00011.ckpt.Is it right?

**Comment by IceClear** [comment]
I think so. You may have a try.

**Comment by flynnamy** [comment]
I have a runtimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select).It should run with one gpu ,right?I found that clip model load by cpu. Any suggestions? Thanks! @IceClear

**Comment by IceClear** [comment]
Hi, it should support multiple gpus, e.g., `--gpus 0,1,2,3,`. I did not meet similar errors. You may need to have a further check.

**Comment by flynnamy** [comment]
Could you please check whether it can be run by one gpu? I only have one gpu,thanks!

**Comment by IceClear** [comment]
I tested on both one gpu and multiple gpus.
