### ISSUE TITLE
Restored from models/v2-1_512-ema-pruned.ckpt with 0 missing and 1242 unexpected keys

### ISSUE THREAD

**Issue by ZhijunHou** [IceClear/StableSR#141]
Hi, there are 1242 unexpected keys, is this normal?

**Comment by wengzp1** [comment]
> Hi, there are 1242 unexpected keys, is this normal?

hello,do you have the problem about the time-aware encoder? When I run python main.py --train --base configs/stableSRNew/v2-finetune_text_T_512.yaml --gpus GPU_ID, --name NAME --scale_lr False,it happened:
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by ZhijunHou** [comment]
> > Hi, there are 1242 unexpected keys, is this normal?
> 
> hello,do you have the problem about the time-aware encoder? When I run python main.py --train --base configs/stableSRNew/v2-finetune_text_T_512.yaml --gpus GPU_ID, --name NAME --scale_lr False,it happened: raise LocalEntryNotFoundError( huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
hi, I think it is caused by the bad connection of hugging face. You can download the open_clip_pytorch_model.bin youself and then put it in the cache folder, **xxx/.cache/huggingface/hub/models--laion-CLIP-ViT-H-14-laion2B-s32B-b79K/open_clip_pytorch_model.bin**, then you can run your program. If not, you can go to the factory.py in open_clip, **xxx/anaconda3/envs/VSFAenv/lib/python3.10/site-packages/open_clip/factory.py**, change the checkpoint_path to the cache path
<img width="616" alt="1722567258848" src="https://github.com/user-attachments/assets/23b0012a-2dd7-4e53-bb19-20eb3b967ce5">

**Comment by wengzp1** [comment]
> > > 你好，有 1242 个意外按键，这是正常的吗？
> > 
> > 
> > 你好，你有关于时间感知编码器的问题吗？当我运行 python main.py --train --base configs/stableSRNew/v2-finetune_text_T_512.yaml --gpus GPU_ID, --name NAME --scale_lr False 时，发生了： raise LocalEntryNotFoundError( huggingface_hub.utils._errors.LocalEntryNotFoundError: 尝试在 Hub 上定位文件时发生错误，我们无法在本地缓存中找到请求的文件。请检查您的连接并重试或确保您的互联网连接已打开。
> > 嗨，我认为这是由于 hugging face 连接不良造成的。您可以自己下载 open_clip_pytorch_model.bin 然后将其放在缓存文件夹**xxx/.cache/huggingface/hub/models--laion-CLIP-ViT-H-14-laion2B-s32B-b79K/open_clip_pytorch_model.bin 中**，然后就可以运行您的程序了。如果没有，你可以进入 open_clip 中的 factory.py **xxx/anaconda3/envs/VSFAenv/lib/python3.10/site-packages/open_clip/factory.py**，将 checkpoint_path 改为缓存路径
> 
> <img alt="1722567258848" width="616" src="https://private-user-images.githubusercontent.com/21111951/354444082-23b0012a-2dd7-4e53-bb19-20eb3b967ce5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTM2OTcsIm5iZiI6MTcyMjU5MzM5NywicGF0aCI6Ii8yMTExMTk1MS8zNTQ0NDQwODItMjNiMDAxMmEtMmRkNy00ZTUzLWJiMTktMjBlYjNiOTY3Y2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEwMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YzY4ZjAxMDFlMDlmYjJmNGEzMDljY2JiMTRiYjY5ODEwY2E1YjBjM2U4YjZkMTczMjMzNmI1YTI0YjRiZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fpO_ADmZWHQL3XeG0--QM8ttd6Sw8Of4eZ8rp_RnksM">

Thank you!I have solved the problem.
