### ISSUE TITLE
StableSR distorts Chinese characters in image

### ISSUE THREAD

**Issue by ITBeyond1230** [IceClear/StableSR#15]
Good work and  thanks for sharing the source code. From the examples shown in the paper, the StableSR works very well to restore text in images, but when I tested it in my image , I found that the model distorted text in images.

The test scripts is scripts/sr_val_ddpm_text_T_vqganfin_old.py， 

the LR image is 
![lr](https://github.com/IceClear/StableSR/assets/12561519/93511e37-868e-453c-b402-f91cf4bdb79c)
and the restored image is 

![restored_hr](https://github.com/IceClear/StableSR/assets/12561519/95303195-00b9-4c41-96e6-ccc795ffc74e)

Do you have any suggestions for that?  Thanks

**Comment by IceClear** [comment]
Hi, this may happen since we did not specifically train StableSR on text data.
Moreover, our current training data does not contain Chinese characters, and I am not sure if Stable Diffusion contains such prior.
You may turn to text SR methods for solutions.

**Comment by ArvinCharl** [comment]
> > Good work and thanks for sharing the source code. From the examples shown in the paper, the StableSR works very well to restore text in images, but when I tested it in my image , I found that the model distorted text in images.
> > The test scripts is scripts/sr_val_ddpm_text_T_vqganfin_old.py，
> > the LR image is ![lr](https://user-images.githubusercontent.com/12561519/239468336-93511e37-868e-453c-b402-f91cf4bdb79c.png) and the restored image is
> > ![restored_hr](https://user-images.githubusercontent.com/12561519/239468610-95303195-00b9-4c41-96e6-ccc795ffc74e.png)
> > Do you have any suggestions for that? Thanks
> 
> Hi, you can refer to our simple text image restoration package (https://github.com/csxmli2016/textbsr) as a post-process.

good job
