### ISSUE TITLE
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch

### ISSUE THREAD

**Issue by ManuBN786** [IceClear/StableSR#151]
I'm trying to train the Train Time-aware encoder with SFT on custom dataset.

The 'train' & 'val' folders are contain HR images in 'gt' and LR images in 'input' folder like this :

![GT_Inputs](https://github.com/user-attachments/assets/0fa59e3c-be49-4be2-903d-45290a48e2f9)

The paths are mentioned in the v2-finetune_text_T_512.yaml are like this:

![paths2](https://github.com/user-attachments/assets/e42e8f8d-dba7-428b-b947-9feb88db8a15)

And I really don't know why the dataloader says there are no image 

![error2](https://github.com/user-attachments/assets/7f8b63cd-84be-48f2-9894-457496682f12)

**Comment by syf2211** [comment]
same with you.Did you solve it?

**Comment by syf2211** [comment]
![image](https://github.com/user-attachments/assets/d1eee12d-4f69-4c7c-9f3f-e21cb0b97e4e)
I know!You need to modify the dataset class because .png is default image file format

**Comment by ManuBN786** [comment]
I changed it to .tif but it sill gives same error as 0 length.

The names of the folders in 'train' are meant to be 'gts' & 'inputs' right?

**Comment by ManuBN786** [comment]
it is just 'tif' and not   '.tif'

So It works now !
