### ISSUE TITLE
Test with multiple GPUs

### ISSUE THREAD

**Issue by rongakowang** [IceClear/StableSR#16]
Hi,

I am aware that the current `sr_val_ddpm_text_T_vqganfin_oldcanvas.py` may have OOM issue for images with high resolutions. However, I wonder if it is possible to run it with multiple GPUs, or is it possible to run the tiling version parallelly on multiple GPUs?

In addition, I wonder what is the expected memory required for an image with resolution 2048 * 1024 without tiling? I am using a 24G 3090 but the memory is not sufficient.

Thank you in advance for your answer!

**Comment by rongakowang** [comment]
Hi @IceClear 

Thank you for your reply! I am managed to perform 2K to 8K super resolution with the GPU mentioned above using the tiling method. However, to do a inference it runs for more than 1h, with each denosing step takes more than 3 minutes. I wonder what makes the denoising process takes such a long time as the standard stable diffusion only takes a few seconds in each inference? Can you confirm if this is the expected speed or is there anything I might do wrong?

Thank you in advance for your answer.

**Comment by IceClear** [comment]
It is normal since we first split the large image into multiple 512 tiles and then deal with each tile separately. A 8k image is similar to dealing with hundreds of 512 images which definitely requires much time. You may reduce the steps, i.e, from 200 to 20 and the time can be reduced significantly.

**Comment by IceClear** [comment]
> Hi,
> 
> Thank you for the quick reply, I understand that multiple samples are needed for image with such resolution. However, I am particular interested in why in each sampling it takes minutes to run while the standard stable diffusion only takes seconds (with the same amount of denoising step): <img alt="屏幕快照 2023-05-24 23 30 28" width="1290" src="https://user-images.githubusercontent.com/45116569/240620110-766339bc-c3b5-429e-b8a5-d43cc8d2e40e.png"> may I ask where could the computation takes most of the time and how may I improve it for each loop?
> 
> Thanks a lot for your answer

I think for tile operation, this time is for each tile of diffusion, i.e., 1280 by default. For each diffusion tile, it also needs to do several diffusion operations on each 512 part. So the time is 4min.
