### ISSUE TITLE
Implementation details about inserting SFT layers

### ISSUE THREAD

**Issue by zhenxili96** [IceClear/StableSR#18]
Hi, I'm reading your code. As Readme said, you trained the Time-aware encoder with **SFT** first, and then trained CFW.

But I noticed that, in the code implementation, the operation for fusing SFT only appears in the `Decoder_Mix` as `fuse_layer`, which is in the CFW runing process.
I didn't notice the "Trainable SFT layer" in unet-related or even time-aware encoder-related codes.

Could you please explain more details about where you inserted SFT layer in unet or time-aware encoder?

**Comment by IceClear** [comment]
We use the [SPADE](https://github.com/IceClear/StableSR/blob/main/ldm/modules/spade.py#L68) for feature fusion in current repo. But the math formulation is identical to SFT shown in the paper.
We do not use SFT for CFW, though there is 'sft' shown in the name. But it actually uses RRDB.
We will further polish the name of modules to avoid misunderstanding.
