### ISSUE TITLE
Get the wired output image when using the pretrained model

### ISSUE THREAD

**Issue by YangGangZhiQi** [IceClear/StableSR#19]
Hi, thanks for your great works. Unlike others getting right SR images using your provided pretrained models, I get the very weird results when using the pretrained model.  The command is as follow:

> python scripts/sr_val_ddpm_text_T_vqganfin_old.py --config configs/stableSRNew/v2-finetune_text_T_512.yaml --ckpt pretrained_models/stablesr_000117.ckpt --vqgan_ckpt pretrained_models/vqgan_cfw_00011.ckpt --init-img inputs/test_example --outdir outputs/user_upload --ddpm_steps 200 --dec_w 0.5 --colorfix_type adain

When using the input image 'inputs/test_example/OST_120.png'， the results likes this:
![OST_120](https://github.com/IceClear/StableSR/assets/87355944/01813989-cd78-43e8-b4ae-0874343633d5)

The command line outputs likes this:
![info1](https://github.com/IceClear/StableSR/assets/87355944/d0be7741-ffef-438b-abc5-9ff2d7ae28a1)
![info2](https://github.com/IceClear/StableSR/assets/87355944/825c54eb-6132-40c5-b98a-c1255386fb83)
![info3](https://github.com/IceClear/StableSR/assets/87355944/8633d933-91ad-481a-bbf6-67680ecdbd07)

I do not know where is the problems. I would appreciate it if anyone could help me.

**Comment by IceClear** [comment]
Hi.
I ran the test but did not get the wired result you showed. You may have a further check.
You may clamp the image to make sure the input range is in [-1, 1].
You may try `--precision full` to avoid half precision.

**Comment by YangGangZhiQi** [comment]
Sorry for my careless for the checkpoint of vqgan. The checkpoint of vqgan is not right.  So the vqgan model is just not initialized by the pretrained model.

> vq_model = load_model_from_config(vqgan_config, opt.vqgan_ckpt)

if opt.vqgan_ckpt would be wrong, there is no hint.  Maybe set verbose=True is saver.
Thanks again for your reply. I will close this issue.
