### ISSUE TITLE
It seems that StableSR uses VAE (VAEGAN) instead of VQGAN.

### ISSUE THREAD

**Issue by USTC-JialunPeng** [IceClear/StableSR#20]
Thanks for your great work! I noticed that StableSR uses `ldm.models.autoencoder.AutoencoderKL` instead of `ldm.models.autoencoder.VQModel` as its pre-trained autoencoder. Since VQGAN has a codebook to quantize continuous feature vectors into discrete feature vectors, is it better to modify the original paper to reduce the ambiguity?

**Comment by IceClear** [comment]
Hi, thanks for your advice.
We have noticed this and will revise our paper later.
