### ISSUE TITLE
Diverse super-resolution results

### ISSUE THREAD

**Issue by USTC-JialunPeng** [IceClear/StableSR#21]
Thanks for your great work! I ran `scripts/sr_val_ddpm_text_T_vqganfin_oldcanvas.py` twice and found the two super-resolution results have slight differences. Is it normal? Looking forward to your reply.

**Comment by IceClear** [comment]
Hi, if you use the same seed, the results should be the same.

**Comment by USTC-JialunPeng** [comment]
Got it. Thanks for the clarification.
