### ISSUE TITLE
train dataset

### ISSUE THREAD

**Issue by kia350** [IceClear/StableSR#24]
hi 
can you share the training dataset ?
DIV8K dataset is hart to download .
thanks

**Comment by kia350** [comment]
ok
can you share more about the detail of making dataset
how many time repeat when use ori photo to make LR  ?

**Comment by IceClear** [comment]
You may refer to the config files for dataset details.

**Comment by kangxi1818** [comment]
thank you for your interesting work, I have a question about the dataset
I now have the inputs and the gts, when I geting the latent and samples, how to set the parameters --init-img of sr_val_ddpm_text_T_vqganfin_old.py to get the latent and samples, and the shape of init_latent is[1,4,64,64]
![image](https://github.com/IceClear/StableSR/assets/117744200/5afc981b-48cf-4e68-a53a-b04ab738088c)
how to save it as .npy
![image](https://github.com/IceClear/StableSR/assets/117744200/c54bfa19-0380-49fa-8980-c33cbc2ee35c)
and how to save the samples as .png

**Comment by IceClear** [comment]
> thank you for your interesting work, I have a question about the dataset I now have the inputs and the gts, when I geting the latent and samples, how to set the parameters --init-img of sr_val_ddpm_text_T_vqganfin_old.py to get the latent and samples, and the shape of init_latent is[1,4,64,64] ![image](https://user-images.githubusercontent.com/117744200/242775572-5afc981b-48cf-4e68-a53a-b04ab738088c.png) how to save it as .npy ![image](https://user-images.githubusercontent.com/117744200/242775774-c54bfa19-0380-49fa-8980-c33cbc2ee35c.png) and how to save the samples as .png

The latents can be obtained from [here](https://github.com/IceClear/StableSR/blob/main/scripts/sr_val_ddpm_text_T_vqganfin_old.py#L315), and the samples can be obtained from [here](https://github.com/IceClear/StableSR/blob/main/scripts/sr_val_ddpm_text_T_vqganfin_old.py#L316). For the gts, they are 512x512 patches and inputs are obtained following the RealESRGAN degradation pipeline.
Use np.save and cv2.imwrite.

**Comment by kangxi1818** [comment]
> 
Thank you for your reply, I have another question, when I run the `sr_val_ddpm_text_T_vqganfin_old.py` to get samples and latents, how to set the `--init-img`
`python scripts/sr_val_ddpm_text_T_vqganfin_old.py --config configs/stableSRNew/v2-finetune_text_T_512.yaml --ckpt CKPT_PATH --vqgan_ckpt VQGANCKPT_PATH --init-img INPUT_PATH --outdir OUT_DIR --ddpm_steps 200 --dec_w 0.5 --colorfix_type adain`
I mean the `INPUT_PATH` 
is it the path of inputs in my dataset
![image](https://github.com/IceClear/StableSR/assets/117744200/476036ce-ee82-4894-8afa-d202461ddfc5)
Thank you very much!!

**Comment by IceClear** [comment]
It is just the name of your test folder. You may refer to the code for details. It is not a secret.

**Comment by kia350** [comment]
> You may refer to the config files for dataset details.
config files is lack of the procedure of how to use real_esrgan make dataset.
and the  test_example/OST_120.png was also made by real_esrgan? 

 when i used real_esrgan to get the lr-hr pair, lr was very hard to distinguish ： 
![0801_s002](https://github.com/IceClear/StableSR/assets/39511502/962c9005-1e24-43a1-bf37-450c6c340bb0)

**Comment by IceClear** [comment]
We just followed RealESRGAN to generate data. You may adjust the pipeline following your settings.
