### ISSUE TITLE
about vqgantile_size and vqgantile_stride

### ISSUE THREAD

**Issue by zcdliuwei** [IceClear/StableSR#25]
is vqgantile_size any integer greater than or equal to 512？

To accelerate inference, I use a smaller vqgantile_size, but when I run the following command：
python sr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py --config configs/stableSRNew/v2-finetune_text_T_512.yaml --ckpt ckpt/stablesr_000117.ckpt --vqgan_ckpt ckpt/vqgan_cfw_00011.ckpt --init-img inputs/ --outdir output --ddpm_steps 60 --dec_w 0.5 --vqgantile_size 530 --vqgantile_stride 500 --upscale 4 --colorfix_type wavelet

I received the following error：
![image](https://github.com/IceClear/StableSR/assets/36565076/31a402fd-7fe8-4e05-b964-2d9caefe0ed4)

But when using vqgantile_size=512, the script is always normal

**Comment by IceClear** [comment]
The tile size should be the multiple of 32.

**Comment by zcdliuwei** [comment]
> qgantile_size any integer greater than or equal to

thanks!
