### ISSUE TITLE
Hello, author. I would like to ask how the files in the "latents" directory under "CFW_trainingdata" are generated?

### ISSUE THREAD

**Issue by wenwenpg** [IceClear/StableSR#28]
Hello, author. I would like to ask how the .npy file under "CFW_trainingdata/latents/00000001.npy" is generated. The article mentions that it is generated from the low-quality (LQ) image. Could you please provide specific information on the code responsible for this process? Thank you very much for your response.

**Comment by IceClear** [comment]
#24
#12
