### ISSUE TITLE
Sampling strategy DDPM vs DDIM

### ISSUE THREAD

**Issue by claudiom4sir** [IceClear/StableSR#39]
Hi, thanks for your excellent work!

I have a question about the sampling strategy. Is there any specific reason why you decided to use DDPM sampling instead of DDIM? DDIM should produce comparable results while requiring considerably fewer iterations. Did you try to use DDIM? If yes, what happened?

Thanks!

Claudio

**Comment by IceClear** [comment]
You may refer to our WebUI which supports various sampling approaches.

**Comment by lyxlynn** [comment]
Hi I wonder whether  ddim_sampling_sr_t in ddpm.py is unfinished code for DDIM implements for stableSR  or not. If I want to use this code to  implement the DDIM sampler not webUI， do I need rewrite ddim_sampling from scratch or just based on ddim_sampling_sr in ddpm.py in your repo?
