### ISSUE TITLE
Tile strategy: CUDA out of memory.

### ISSUE THREAD

**Issue by msk7131** [IceClear/StableSR#4]
execute this tile  command  :
	python scripts/sr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py --config configs/stableSRNew/v2-finetune_text_T_512.yaml --ckpt CKPT_PATH --vqgan_ckpt VQGANCKPT_PATH --init-img INPUT_PATH --outdir OUT_DIR --skip_grid --ddpm_steps 200 --dec_w 0.5

still  CUDA out of memory.
my cuda memory size is  15G

Is there any way to solve this problem？

**Comment by IceClear** [comment]
Hi~
For tile operation, we currently use a very large tile by default, see [here](https://github.com/IceClear/StableSR/blob/main/scripts/sr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py#L361).
You can see the tile size is 1280 (in pixel space), and the stride is 1000.
If you would like to save GPU memory, you may need to reduce the tile size accordingly (larger than 512).
The tile operation may lead to border artifacts, so we recommend setting the tile as large as you can.

Also, you need to check whether xformers works well in your env. It also largely saves the memory.
Hoping the strategies can solve your problem.

**Comment by IceClear** [comment]
> Hi~ For tile operation, we currently use a very large tile by default, see [here](https://github.com/IceClear/StableSR/blob/main/scripts/sr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py#L361). You can see the tile size is 1280 (in pixel space), and the stride is 1000. If you would like to save GPU memory, you may need to reduce the tile size accordingly (larger than 512). The tile operation may lead to border artifacts, so we recommend setting the tile as large as you can.
> 
> Also, you need to check whether xformers works well in your env. It also largely saves the memory. Hoping the strategies can solve your problem.

I further remove some unimportant operation in the test file to further reduce memory cost. Now, 16G should be enough for most cases with a slightly smaller tile, e.g., 1024 : )
