### ISSUE TITLE
Stuck in epoch 0%

### ISSUE THREAD

**Issue by misi0202** [IceClear/StableSR#44]
When I want to train SFT, the process get stuck in epoch 0:0% for long time,I have normal result in test
The CLI i use
`python main.py --train --base configs/stableSRNew/v2-finetune_text_T_512.yaml --gpus 0, --name NAME --scale_lr False`
![image](https://github.com/IceClear/StableSR/assets/101965629/4768447d-e39e-49a4-878b-585c0f3eefb9)

Have anyboby has some ideas to solve?

**Comment by IceClear** [comment]
Hi, could you please have a check about where the code is stuck? It is hard to say what the problem is without error info :(

**Comment by IceClear** [comment]
See the code [here](https://github.com/IceClear/StableSR/blob/main/basicsr/data/realesrgan_dataset.py#L146).

**Comment by misi0202** [comment]
Thanks for your reply! I thought it is my dataset have problem,so I change the dataset to DIV2K and put it low scale in LQ,but my dataloader cant read data successfully.(I test the path I set is right,it can read all png name in code)

**Comment by misi0202** [comment]
> @IceClear Thanks for your reply! I thought it is my dataset have problem,so I change the dataset to DIV2K and put it low scale in LQ now. When I try to train ,it failed by cuda out of memory, I am trying to slove. I want to know if the pic too big?(most 2048*1356) I turn down num_workers but it seems like unuseful,have there has some params should to set? ![截屏2023-07-12 20 38 33](https://user-images.githubusercontent.com/101965629/253152745-22d04289-0489-4544-9e77-bfbfa94f004a.png) It occured at epoch0 :)

I down the batch_size to 4,it trained slowly
