### ISSUE TITLE
Inability to fetch new data.

### ISSUE THREAD

**Issue by Suummqq** [IceClear/StableSR#47]
Thank you for your contribution. When I try to switch to other data, such as scientific data with three dimensions, for training, I initially can fetch the data correctly. However, it gets stuck in the middle of the first epoch, and upon debugging, I found that the trainer's queue is not adding new data continuously. Could you please advise on which parameter I can modify to allow my training to proceed?
![image](https://github.com/IceClear/StableSR/assets/106465377/ebb37c9f-e1d3-41af-89b8-2fb5d43e8a89)
Using the original dataloader to fetch data is completely normal.

**Comment by IceClear** [comment]
I guess the problem is [here](https://github.com/IceClear/StableSR/blob/main/basicsr/data/realesrgan_dataset.py#L146)

**Comment by Suummqq** [comment]
Thank you for your response. I realized that the lack of strict normalization of the data to the range of (0,1) caused this.







> I guess the problem is [here](https://github.com/IceClear/StableSR/blob/main/basicsr/data/realesrgan_dataset.py#L146).
