### ISSUE TITLE
Why does this error occur?

### ISSUE THREAD

**Issue by ARTUROSING** [IceClear/StableSR#5]
Traceback (most recent call last):
  File "/content/StableSR/scripts/sr_val_ddpm_text_T_vqganfin_old.py", line 4, in <module>
    import PIL
ModuleNotFoundError: No module named 'PIL'

All the libraries were installed, I previously translated the Google Colab notebook to another language.
Every time I get this error, every time I start up.

**Comment by IceClear** [comment]
Hi~
Did you try `pip install pillow`?
Sry that I think I may miss it in the env.yaml.

**Comment by Ivan29B** [comment]
You also said about not testing the Google Colab laptop for stability.

I think that, one of the problems that you could not foresee.I hope that you will fix it)

Thank you very much, for your attention.
