### ISSUE TITLE
have you tried replace ddpm with ddim？

### ISSUE THREAD

**Issue by cv-nlp** [IceClear/StableSR#51]
have you done some comparison

**Comment by IceClear** [comment]
#39

**Comment by cv-nlp** [comment]
> #39
I meet a error when training CFW module,the tensor shape print like,enc_feat: torch.Size([1, 512, 512, 512]) 	dec_feat: torch.Size([1, 512, 128, 128]).thanks.

  File "****diffusionmodules/model.py", line 831, in forward
    enc_feat = self.encode_enc_1(torch.cat([enc_feat, dec_feat], dim=1))
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 512 but got size 128 for tensor number 1 in the list.
