### ISSUE TITLE
CFW training issue

### ISSUE THREAD

**Issue by Dexter1066** [IceClear/StableSR#52]
Hello author,
I'm trying to fine-tune CFW module using your guidelines to prepare CFW training data. I've acquired the inputs and gts, and latents and samples are also saved locally. The size of inputs, gts and samples are all 512 x 512.

However, during the training process I encountered the following error:
<img width="812" alt="image" src="https://github.com/IceClear/StableSR/assets/60422124/9b79d3d6-69c7-482a-97de-efd7a7a15905">
 
I think it has something to do with the training data, but I am unable to locate the problem.

**Comment by IceClear** [comment]
#12 The latent should be (N, 4, 64, 64)

**Comment by Dexter1066** [comment]
Thank you very much! I save the latents in the wrong shape. Problem solved.
