### ISSUE TITLE
DDIM usage

### ISSUE THREAD

**Issue by jackheisenberg934** [IceClear/StableSR#73]
I am not able to use DDIM sampling even though DDIMSampler class is present.
How do i use it?

**Comment by IceClear** [comment]
This repo does not support DDIM currently. You may refer to our WebUI repo which supports various sampling. See #39 .

**Comment by lyxlynn** [comment]
Hi I wonder whether ddim_sampling_sr_t in ddpm.py is unfinished code for DDIM implements for stableSR or not. If I want to use this code to implement the DDIM sampler not webUI， do I need rewrite ddim_sampling from scratch or just based on ddim_sampling_sr in ddpm.py in your repo?
