### ISSUE TITLE
Restored from /mnt/lustre/jywang/code/stable_diffmodels/v2-1_512-ema-pruned.ckpt with 376 missing and 2 unexpected keys

### ISSUE THREAD

**Issue by han48614284** [IceClear/StableSR#83]
Thanks for sharing your excellent work~
When I run the command to train Time-aware encoder with SFT, there is a message saying "Restored from /mnt/lustre/jywang/code/stable_diffmodels/v2-1_512-ema-pruned.ckpt with 376 missing and 2 unexpected keys". I wonder whether it's an error or not. If not, do the missing keys  belong to the SFT layers? Thank you very much~

**Comment by IceClear** [comment]
Hi.
You may check the name of the parameters, Generally, this is expected since we only load the pre-trained model and parameters from time-aware encoder and SFT are missing.

**Comment by han48614284** [comment]
Thank you.
