### ISSUE TITLE
encode LR first or crop LR first?

### ISSUE THREAD

**Issue by Anonym0u3** [IceClear/StableSR#94]
Hello First of all thanks for this outstanding work but I have some questions to ask as follows: I read in the paper that it is the LR that are converted to latent features and then they are cropped, but in the code I found that it is the LR that are cropped first and then converted to latent features for each cropped patch, may I ask what is the correct operation?

**Comment by IceClear** [comment]
Hi. May I know which part of the code you refer to? I guess you are looking at the code for large image SR where we first crop large images beyond 1K into patches and then adopt SR on each.

**Comment by Anonym0u3** [comment]
![1](https://github.com/IceClear/StableSR/assets/110756446/11e925bb-c25a-4175-8033-95d7a21b2bd4)
![2](https://github.com/IceClear/StableSR/assets/110756446/24f7eb4d-0e93-42c5-993d-a9553f4c919f)
thank you for the reply! Like you said, I'm looking for the code for large large image SR,so i get confused here.

**Comment by IceClear** [comment]
Hi. For very large images, the GPU memory is not enough and we have to first crop the large images and then use the strategy above. In theory, you do not have to do this if you have enough GPU memory.
